language: python

sudo: false

python:
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'

addons:
  apt:
    packages:
      - trang

install:
  - pip install lxml
  - pip install nose

  - trang -I rnc -O rng citeproc/data/schema/csl.rnc citeproc/data/schema/csl.rng

script:
  - nosetests
  - PYTHONPATH="." python tests/citeproc-test.py
