language: python

sudo: false

python:
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'

addons:
  apt:
    packages:
      - trang

install:
  - pip install tox-travis
  - trang -I rnc -O rng citeproc/data/schema/csl.rnc citeproc/data/schema/csl.rng

script:
  - tox
